version: '3'
services:
  api:
    image: sample-express-app
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"

  web-cli:
    image: sample-express-app
    networks:
      - backend
    command: sh

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres

networks:
  backend:
    driver: bridge
    